<?php

use App\Http\Controller\Database\DBHelpers;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::dropIfExists('zreadings');

        Schema::create('zreadings', function (Blueprint $table) {
            $helper = new DBHelpers();
            $table->id();
            $table->integer('counter')->default(1);
            $table->double('transactions', 15, 2)->default(0);
            $table->double('cash', 15, 2)->default(0);
            $table->double('e_wallet', 15, 2)->default(0);
            $table->double('refund', 15, 2)->default(0);
            $table->double('vat_on_refunds', 15, 2)->default(0);
            $table->double('net_sales', 15, 2)->default(0);
            $table->double('vatable', 15, 2)->default(0);
            $table->double('vat', 15, 2)->default(0);
            $table->double('vat_exempt', 15, 2)->default(0);
            $table->double('zero_rated', 15, 2)->default(0);
            $table->double('reg_discount', 15, 2)->default(0);
            $table->double('sc_discount', 15, 2)->default(0);
            $table->double('pwd_discount', 15, 2)->default(0);
            $table->double('solo_parent_discount', 15, 2)->default(0);
            $table->double('naac_discount', 15, 2)->default(0);
            $table->double('vat_special_discounts', 15, 2)->default(0);
            $table->double('sc_vat_adjustment', 15, 2)->default(0);
            $table->double('pwd_vat_adjustment', 15, 2)->default(0);
            $table->double('sp_vat_adjustment', 15, 2)->default(0);
            $table->double('naac_vat_adjustment', 15, 2)->default(0);
            $table->double('sc_transactions', 15, 2)->default(0);
            $table->double('pwd_transactions', 15, 2)->default(0);
            $table->double('sp_transactions', 15, 2)->default(0);
            $table->double('naac_transactions', 15, 2)->default(0);
            $table->double('reg_disc_transactions', 15, 2)->default(0);
            $table->string('first_or');
            $table->string('last_or');
            $table->string('begin_date');
            $table->string('end_date');
            $table->double('previous_accumulated_sales', 15, 2)->default(0);
            $table->double('present_accumulated_sales', 15, 2)->default(0);
            $helper->addBillsAndCentsDenomination($table);
            $table->double('discrepancy', 15, 2);
            // Foreign Keys
            $table->integer('user_id')->unsigned()->index('user_id'); // Generated by
            $table->integer('pos_id')->unsigned()->index('pos_id');
            $table->integer('store_id')->unsigned()->index('store_id');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('zreadings');
//        Artisan::call('artisan migrate', ['--path' => '/database/migrations/2021_06_17_113612_create_zreadings_table.php']);
//        Artisan::call('artisan migrate', ['--path' => '/database/migrations/2021_09_01_214426_add_excess_to_zreadings_table.php']);
//        Artisan::call('artisan migrate', ['--path' => '/database/migrations/2021_09_03_153512_add_cash_in_to_zreadings_table.php']);
//        Artisan::call('artisan migrate', ['--path' => '/database/migrations/2021_09_03_155901_add_non_vat_to_zreadings_table.php']);
//        Artisan::call('artisan migrate', ['--path' => '/database/migrations/2021_09_03_155901_add_non_vat_to_zreadings_table.php']);
//        Artisan::call('artisan migrate', ['--path' => '/database/migrations/2023_02_19_210737_add_excess_vatable_to_zreadings_table.php']);
    }
};
