<?php

use App\Http\Controller\Database\DBHelpers;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateNewXreadingsTable extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Drop old xreadings table if exists
        Schema::dropIfExists('xreadings');
        $helper = new DBHelpers();
        // Create new xreadings table
        Schema::create('xreadings', function (Blueprint $table) use ($helper) {
            $table->id();
            $table->dateTime('reading_at');
            $table->dateTime('start_at');
            $table->dateTime('end_at');
            $table->string('beginning_or');
            $table->string('ending_or');
            $table->double('opening_fund', 15, 2);
            // Payments received
            $table->double('cash', 15, 2);
            $table->double('e_wallet', 15, 2);
            // Adjustments
            $table->double('refunds', 15, 2);
            $table->double('withdrawals', 15, 2);
            // Transaction Summary
            $table->double('cash_in_drawer', 15, 2);
            // Add denomination
            $helper->addBillsAndCentsDenomination($table);
            // Summary
            $table->double('discrepancy', 15, 2);
            // Foreign Keys
            $table->integer('user_id')->unsigned()->index('user_id'); // Generated by
            $table->integer('pos_id')->unsigned()->index('pos_id');
            $table->integer('store_id')->unsigned()->index('store_id');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('xreadings');
//        Artisan::call('artisan migrate', ['--path' => '/database/migrations/2021_06_17_190000_create_xreadings_table.php']);
//        Artisan::call('artisan migrate', ['--path' => '/database/migrations/2021_09_01_214419_add_excess_to_xreadings.php']);
//        Artisan::call('artisan migrate', ['--path' => '/database/migrations/2021_09_01_153413_cash_in_to_xreadings.php']);
//        Artisan::call('artisan migrate', ['--path' => '/database/migrations/2021_09_01_155925_non_vat_to_xreadings.php']);
//        Artisan::call('artisan migrate', ['--path' => '/database/migrations/2021_09_01_155925_non_vat_to_xreadings.php']);
//        Artisan::call('artisan migrate', ['--path' => '/database/migrations/2024_05_11_231015_name_for_to_to_first_or_in_xreadings.php']);
    }
};
